[env:reterminal_e1002]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi   ; 8MB OPI PSRAM
board_build.flash_size = 32MB
board_build.partitions = default_16MB.csv
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -I include                                 ; so Seeed_GFX finds driver.h
lib_deps =
  https://github.com/Seeed-Studio/Seeed_GFX.git
  https://github.com/bblanchon/ArduinoJson.git
